// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: relay.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayService_ReservePeerRelay_FullMethodName = "/meshlink.v1.RelayService/ReservePeerRelay"
	RelayService_ReleasePeerRelay_FullMethodName = "/meshlink.v1.RelayService/ReleasePeerRelay"
)

// RelayServiceClient is the client API for RelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayServiceClient interface {
	ReservePeerRelay(ctx context.Context, in *ReservePeerRelayRequest, opts ...grpc.CallOption) (*ReservePeerRelayResponse, error)
	ReleasePeerRelay(ctx context.Context, in *ReleasePeerRelayRequest, opts ...grpc.CallOption) (*ReleasePeerRelayResponse, error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) ReservePeerRelay(ctx context.Context, in *ReservePeerRelayRequest, opts ...grpc.CallOption) (*ReservePeerRelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservePeerRelayResponse)
	err := c.cc.Invoke(ctx, RelayService_ReservePeerRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) ReleasePeerRelay(ctx context.Context, in *ReleasePeerRelayRequest, opts ...grpc.CallOption) (*ReleasePeerRelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleasePeerRelayResponse)
	err := c.cc.Invoke(ctx, RelayService_ReleasePeerRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServiceServer is the server API for RelayService service.
// All implementations must embed UnimplementedRelayServiceServer
// for forward compatibility.
type RelayServiceServer interface {
	ReservePeerRelay(context.Context, *ReservePeerRelayRequest) (*ReservePeerRelayResponse, error)
	ReleasePeerRelay(context.Context, *ReleasePeerRelayRequest) (*ReleasePeerRelayResponse, error)
	mustEmbedUnimplementedRelayServiceServer()
}

// UnimplementedRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) ReservePeerRelay(context.Context, *ReservePeerRelayRequest) (*ReservePeerRelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservePeerRelay not implemented")
}
func (UnimplementedRelayServiceServer) ReleasePeerRelay(context.Context, *ReleasePeerRelayRequest) (*ReleasePeerRelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleasePeerRelay not implemented")
}
func (UnimplementedRelayServiceServer) mustEmbedUnimplementedRelayServiceServer() {}
func (UnimplementedRelayServiceServer) testEmbeddedByValue()                      {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServiceServer will
// result in compilation errors.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	// If the following call pancis, it indicates UnimplementedRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

func _RelayService_ReservePeerRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservePeerRelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ReservePeerRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ReservePeerRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ReservePeerRelay(ctx, req.(*ReservePeerRelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_ReleasePeerRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePeerRelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ReleasePeerRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ReleasePeerRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ReleasePeerRelay(ctx, req.(*ReleasePeerRelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayService_ServiceDesc is the grpc.ServiceDesc for RelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meshlink.v1.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReservePeerRelay",
			Handler:    _RelayService_ReservePeerRelay_Handler,
		},
		{
			MethodName: "ReleasePeerRelay",
			Handler:    _RelayService_ReleasePeerRelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay.proto",
}
